#%RAML 0.8
title: Cloud File Storage
version: 0.1
baseUri: http://localhost:5999/
protocols: [HTTP]
mediaType: application/json

/users:
  description: users entity
  get:
    description: get all users
    responses:

  post:
    description: create new user
  /{userId}:
    description: user entity
    get:
      description: get one user by its id, 404 if id not found
    patch:
      description: change user by its id
    delete:
      description: delete user by its id

/assets:
  description: folder structure
  get:
    description: get all assets
  post:
    description: create new asset
  /folder/{folderId}:
    get:
      description: get one folder by its id
    post:
      description: create new asset
    put:
      description: change folder by its id
    delete:
      description: delete folder by its id
  /file/{fileId}:
    get:
      description: get one file by its id
    put:
      description: change file by its id
    delete:
      description: delete file by its id

/resources:
  description: checking used resources
  get:
    description: get used resources for whole system
  /{resourceId}:
    get:
      description: get used resources for specific resource
